# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := VAHD-Projekt

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

VAHD-Projekt: 
	@echo "==== Building VAHD-Projekt ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f VAHD-Projekt.make

clean:
	@${MAKE} --no-print-directory -C . -f VAHD-Projekt.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   VAHD-Projekt"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
